Repository DevAffan/AffiCodes-Hacktoberfest2024, pull requests merged in 2023-10, with the labels that each got.

#48 Squaring the numbers using normal and arrow function
  PHP/Squared_Numbers/README.md
  PHP/Squared_Numbers/arrow_fucntion.php
Labels: hacktoberfest-accepted

#49 Sorting emails with domain names
  PHP/SortEmailsWithDomainName/README.md
  PHP/SortEmailsWithDomainName/sort_emails.php
Labels: hacktoberfest, hacktoberfest-accepted

#50 added a php algorithm of removing duplicates and sorting array
  PHP/DuplicateEntries/DuplicateEntries.php
  PHP/DuplicateEntries/README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#51 Contribute to main readme.md file
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#52 added validParenthesis
  C++/validParenthesis.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#55 Create ImageDetection.py
  ImageDetection.py
Labels: hacktoberfest, hacktoberfest-accepted

#56 todo react and typescript
  Mini_projects/react_todo_youtube-main/.eslintrc.cjs
  Mini_projects/react_todo_youtube-main/.gitignore
  Mini_projects/react_todo_youtube-main/index.html
  Mini_projects/react_todo_youtube-main/package-lock.json
  Mini_projects/react_todo_youtube-main/package.json
  Mini_projects/react_todo_youtube-main/public/vite.svg
  Mini_projects/react_todo_youtube-main/src/App.css
  Mini_projects/react_todo_youtube-main/src/App.tsx
  Mini_projects/react_todo_youtube-main/src/assets/react.svg
  Mini_projects/react_todo_youtube-main/src/components/addtodo.tsx
  Mini_projects/react_todo_youtube-main/src/components/navbar.tsx
  Mini_projects/react_todo_youtube-main/src/components/todos.tsx
  Mini_projects/react_todo_youtube-main/src/index.css
  Mini_projects/react_todo_youtube-main/src/main.tsx
  Mini_projects/react_todo_youtube-main/src/store/todos.tsx
  Mini_projects/react_todo_youtube-main/src/vite-env.d.ts
  Mini_projects/react_todo_youtube-main/tsconfig.json
  Mini_projects/react_todo_youtube-main/tsconfig.node.json
  Mini_projects/react_todo_youtube-main/vite.config.ts
Labels: hacktoberfest, hacktoberfest-accepted

#58 tyopescript ecommerce assignemt
  Mini_projects/e-commerece/.gitignore
  Mini_projects/e-commerece/ecommerce.js
  Mini_projects/e-commerece/ecommerce.ts
  Mini_projects/e-commerece/package-lock.json
  Mini_projects/e-commerece/package.json
Labels: hacktoberfest, hacktoberfest-accepted

#59 typescript atm code
  Mini_projects/atm_typescript/.gitignore
  Mini_projects/atm_typescript/assignments.txt
  Mini_projects/atm_typescript/atm.html
  Mini_projects/atm_typescript/atm.js
  Mini_projects/atm_typescript/atm.ts
  Mini_projects/atm_typescript/package-lock.json
  Mini_projects/atm_typescript/package.json
Labels: hacktoberfest, hacktoberfest-accepted
