Repository DevAffan/AffiCodes-Hacktoberfest2024, pull requests merged in 2024-10, with the labels that each got.

#67 Dijkstra code added
  Java/Dijkstra.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#69 inorder tree traversal | hacktoberfest2024
  Python/inorder_tree_traversal.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#70 Added SelectionSort.java
  .idea/.gitignore
  .idea/AffiCodes-Hacktoberfest2024.iml
  .idea/material_theme_project_new.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Java/SelectionSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#72 Tortoise Hare Algorithm
  Java/ListNode.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#73 Added a tictactoe game designed using Tkinter in Python
  Mini_projects/tic-tac-toe-game/tictactoe.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#74 Add Selection Sort implementation in Java
  Java/Insertion_Sort.java
  Java/Selection_Sort.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#83 Add Binary Search in java #78 , Task Completed.
  Java/Binary_Search.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#85 Added Binary_Search code in java
  Java/BinarySearch.java
  Java/Insertion_Sort.java
Labels: duplicate, hacktoberfest, hacktoberfest-accepted

#86 Create fibonacciSeries
  Python/fibonacciSeries
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#94 Create binarySearch.py
  Python/binarySearch.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#89 Create basicCalculator.py
  Python/basicCalculator.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#96 Create TicTacToe.c
  C/tic-tac-toe.c
  TicTacToe.c
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#84 resolved the #78 (Implement Binary Search Functionality in C++)
  C++/binary_serach/.cph/.binary_search.cpp_01234da0c80f430aba771c5b80d99321.prob
  C++/binary_serach/binary_search.bin
  C++/binary_serach/binary_search.cpp
Labels: duplicate, hacktoberfest, hacktoberfest-accepted

#98 Create checkLeapYear.py
  Python/checkLeapYear.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#92 Add Graph traveral using BFS and DFS in Java
  Java/BFS_graph.java
  Java/DFS_graph.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#88 Create checkArmstrongNumber.py
  Python/checkArmstrongNumber.py
Labels: hacktoberfest, hacktoberfest-accepted

#99 Create checkPrimeNumber.py
  Python/checkPrimeNumber.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#101 Proposal: Adding an implementation of the Huffman Coding algorithm in Java #95, Task Compleated.
  Java/HuffmanCoding.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#106 Create generateRandomNumber.py
  Python/generateRandomNumber.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#107 Create findFactorial.py
  Python/findFactorial.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#119 Floyd-Warshall Algortihm in Java
  Java/Floyd_Warshall.java
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024, Ideas

#108 Created Floyd-Warshall-Algorithm.cpp
  C++/Floyd-Warshall-Algorithm.cpp
Labels: good first issue, question, hacktoberfest, Hacktoberfest2024, Contributions

#123 Adding Two Sum using brute Force
  C++/twosumBruteForce.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#125 Update README.md
  JavaScript/README.md
Labels: documentation, enhancement, help wanted, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024, Contributions

#126 Added readme for c #117
  C/README_C.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024, Contributions

#128 Create LIS.cpp
  LIS.cpp
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#129 Added Knapsack.java File
  Java/Knapsack.java
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#130 Create Count and say.java
  Java/Count_and_say.java
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#133 Update README.md
  C++/README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#139 Enhance README for Java Folder: Improved Clarity and Structure
  Java/README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024, Contributions

#136 Create Volume_controller.py
  Mini_projects/Volume_controller.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#140 Update Kadane's Algorithm
  C++/Maximum Subarray Sum – Kadane’s Algorithm.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#138 Proposal : Adding an implementation of the A* (A-Star) pathfinding al…
  Python/a_star.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#137 Create Turtle_race.py
  Mini_projects/Turtle_race.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024, Contributions

#141 QuickSort.java added
  Java/QuickSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#142 HeapSort.java Added
  Java/HeapSort.java
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#143 added floydwarshall algorithm code and explained in details
  C++/floydwarshallalgorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#146 Create Payment_QR.py
  Python/Payment_QR.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#147 Create Blind_bid.py
  Python/Blind_bid.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#148 Singly Linked List using C
  C/singly_linked_list.c
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#149 Add: KMPAlgorithm.java
  Java/KMPAlgorithm.java
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#154 Job Scheduling Problem in Python. #145
  Python/job_scheduling.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#157 Armstrong number in cpp
  C++/Armstrong number.cpp
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#167 PHP README file Updated
  PHP/README.md
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#179 Provided KMP code
  Java/KMP_Algo.java
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#170 Add Robot Bounded In Circle.cpp
  C++/Robot Bounded In Circle.cpp
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#187 Line Sweep Code in java
  Java/LineSweep.java
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#189 Python README file Updated
  Python/README.md
Labels: help wanted, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#182 update readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#181 Coin change in cpp
  C++/coin change.cpp
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#172 Create Boyer-Moore Algorithm in Java
  Boyer-Moore Algorithm in Java
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#183 Add programming problem in Python
  Python/findKClosest.py
  Python/threeSumClosest.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#198 Cherry Pickup in cpp
  C++/Cherry Pickup.cpp
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#177 Added implementations for Heap Sort and Shell Sort algorithms
  C++/HeapSort.cpp
  C++/ShellSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#191 Add implementation of Data Structure (BST & LinkedList)
  JavaScript/Data Structure/binarySearchTree.js
  JavaScript/Data Structure/linkedlist.js
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#192 Added 2D list spiral print and Merge 2 sorted array
  Python/2D_list_spiral_print.py
  Python/merge_two_sorted_arrays.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#196 binarySearch.c using dynamic memory allocation added
  C/binarySearch.c
  C/stacks_with_linked_lists.c
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#197 Create 3Sum.py
  Python/3Sum.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#199 Create binarytree.c
  C/binarytree.c
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#200 Enhance python README with Detailed Project Overview and Contributions
  Python/README.md
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#151 added Smart Pointers Code
  C++/SmartPointers/.gitignore
  C++/SmartPointers/main.cpp
  C++/SmartPointers/main.exe
  C++/SmartPointers/sharedptr.cpp
  C++/SmartPointers/sharedptr.exe
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#202 Added code for min heap implementation in Python
  Python/min_heap.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#203 Added code for max heap in py
  Python/max_heap.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#204 Added QR code generator
  Mini_projects/qr code/index.html
  Mini_projects/qr code/script.js
  Mini_projects/qr code/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#205 Create stack.c
  C/stack.c
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#208 Added Linear search
  Java/Linear_Search.java
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#211 Updated Merge Sort in Python
  Python/merge_sort.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#210 feat : Added 5 new problems that are for beginners with explanation in c++
  BasicQuestions/cpp/cpp/Employee Management System (OOP with File Handling).cpp
  BasicQuestions/cpp/cpp/Fibonacci.cpp
  BasicQuestions/cpp/cpp/Find the Sum of Digits of a Number.cpp
  BasicQuestions/cpp/cpp/Implement a Simple Todo List Application.cpp
  BasicQuestions/cpp/cpp/Matrix Multiplication.cpp
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#209 Update checkPalindromeNumber.py
  Python/checkPalindromeNumber.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#215 Python and C program
  C/duplicate number.c
  Python/maximum depth of binary tree.py
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#228 Knapsack with example #104
  Java/Knapsack_algo.java
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#221 Create Maximum Rectangle Area with all 1's
  C++/MaximumRectangleAreawithall1/MaximumRectangleAreawithall1.cpp
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024

#266 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, Hacktoberfest2024
